name: civet
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - iqtree<2
  - mafft
  - minimap2
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal=5.13
  - libpysal=4.3.0
  - nodejs=10.12.0
  - pip:
    - pandas==1.0.1
    - pytools==2020.1
    - dendropy>=4.4.0
    - tabulate>=0.8.7
    - grip>=4.5.2
    - descartes>=1.1.0
    - git+https://github.com/cov-ert/datafunk.git
    - git+https://github.com/cov-ert/clusterfunk.git

