report: Outbreak # the report template to use

title: COG Situation report
outbreak-id: Sitrep
report_date: 2020-10-07 # date investigation was opened
authors: Verity, Ãine, Andrew # List of authors, affiliations and contact details
description: > # Free-text description that will be inserted at the top of the report - can use markdown for formatting. Please use \n to indicate new lines.
  ### Background \n
  This report describes the current situation of outbreak across the UK. It shows all sequences sampled in the last two weeks.
conclusions: > # Free-text concluding text that will be inserted at the bottom of the report
  ### Conclusions \n
  There is still active circulation in all areas of the UK
omit_appendix: False
include_snp_table: True
node_summary: country
up-distance: 2
down-distance: 2
threshold: 1
from-metadata: ["sample_date=2020-09-22:2020-10-06"]
date-fields: ["sample_date", "date_2", "date_3"]
safety_level: 0 #as if it were run on CLIMB
include_bars: True
map_sequences: True
map_info: adm2
local_lineages: False

